# Generated by Django 4.1.2 on 2023-06-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('hot', 'hot'), ('type', 'type'), ('sugar', 'sugar'), ('nut', 'nut'), ('size', 'size')], max_length=100),
        ),
    ]
